#!/bin/bash -ex

ADMIN_USER="administrator"
ADMIN_PASS="turnkey"
ADMIN_MAIL="admin@example.com"

DB_NAME=gnusocial
DB_USER=gnusocial
DB_PASS=$(mcookie)

WEBROOT=/var/www/gnusocial

# unpack tarball to webroot and set permissions
tar -zxf /usr/local/src/gnusocial.tar.gz -C /var/www/
rm -f /usr/local/src/gnusocial.tar.gz
mv /var/www/gnu-social-* /var/www/gnusocial

# fix missing dirs
mkdir -p /var/www/gnusocial/{avatar,background,file}

chown -R www-data:www-data $WEBROOT

# setup database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

/etc/init.d/mysql start
$MYSQL_ADMIN create $DB_NAME

$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# update apache configuration
a2dissite 000-default
a2ensite gnusocial
a2enmod rewrite

# complete the installation
/etc/init.d/apache2 start
URL="http://127.0.0.1/install.php"
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)

curl --data "sitename=TurnKey+GNU+social&ssl=always&host=localhost&dbtype=mysql&database=$DB_NAME&dbusername=$DB_USER&dbpassword=$DB_PASS&admin_nickname=$ADMIN_USER&admin_password=$ADMIN_PASS&admin_password2=$ADMIN_PASS&admin_email=$EMAIL&admin_updates=false&site_profile=public&submit=Submit" $URL

# delete confirmation mail to $ADMIN_MAIL
rm -f /var/spool/postfix/maildrop/*

# stop services
/etc/init.d/apache2 stop
/etc/init.d/mysql stop

