#!/bin/bash -ex

ADMIN_USER="administrator"
ADMIN_PASS="turnkey"
ADMIN_MAIL="admin@example.com"

DB_NAME=statusnet
DB_USER=statusnet
DB_PASS=$(mcookie)

WEBROOT=/var/www/statusnet

# unpack tarball to webroot and set permissions
tar -zxf /usr/local/src/statusnet-*.tar.gz -C /var/www/
mv /var/www/statusnet-* $WEBROOT
rm -f /usr/local/src/statusnet-*.tar.gz

chown -R www-data:www-data $WEBROOT

# convenience execution variables
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

# start mysql server
/etc/init.d/mysql start

# create database
$MYSQL_ADMIN create $DB_NAME

# create database user with privileges on the database
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# update apache configuration
a2dissite default
a2ensite statusnet
a2enmod rewrite

# complete the installation
/etc/init.d/apache2 start
URL="http://127.0.0.1/install.php"
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)

curl --data "sitename=TurnKey+StatusNet&fancy=enable&host=localhost&dbtype=mysql&database=$DB_NAME&dbusername=$DB_USER&dbpassword=$DB_PASS&admin_nickname=$ADMIN_USER&admin_password=$ADMIN_PASS&admin_password2=$ADMIN_PASS&admin_email=$EMAIL&admin_updates=false&site_profile=public&submit=Submit" $URL

# delete confirmation mail to $ADMIN_MAIL
rm -f /var/spool/postfix/maildrop/*

# stop services
/etc/init.d/apache2 stop
/etc/init.d/mysql stop

