#!/bin/bash -e
# regenerate statusnet secrets

. /etc/default/inithooks

updateconf() {
    CONF=/var/www/statusnet/config.php
    sed -i "s|statusnet:\(.*\)@|statusnet:$1@|" $CONF
}

PASSWORD=$(mcookie)

updateconf $PASSWORD
$INITHOOKS_PATH/bin/mysqlconf.py --user=statusnet --pass="$PASSWORD"

