#!/bin/bash -e
# regenerate GNU social secrets

. /etc/default/inithooks

updateconf() {
    CONF=/var/www/gnusocial/config.php
    sed -i "s|gnusocial:\(.*\)@|gnusocial:$1@|" $CONF
}

PASSWORD=$(mcookie)

updateconf $PASSWORD
$INITHOOKS_PATH/bin/mysqlconf.py --user=gnusocial --pass="$PASSWORD"

