#!/bin/bash -e
# set GNU social domain, administrator password and email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/gnusocial.py --pass="$APP_PASS" --email="$APP_EMAIL"

